# Generated by Django 5.1 on 2024-11-15 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("materials", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active.",
                verbose_name="active",
            ),
        ),
        migrations.CreateModel(
            name="Pyment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата платежа")),
                (
                    "amount",
                    models.PositiveIntegerField(help_text="Укажите сумму платежа", verbose_name="Сумма платежа"),
                ),
                (
                    "pyment_method",
                    models.CharField(
                        blank=True,
                        choices=[("cach", "Наличными"), ("transfer", "Перевод на счет")],
                        default="cach",
                        help_text="Укажите способ платежа",
                        max_length=8,
                        verbose_name="Способ платежа",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите курс для оплаты",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pyments_course",
                        to="materials.course",
                        verbose_name="Оплаченный курс",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите урок для оплаты",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pyments_lesson",
                        to="materials.lesson",
                        verbose_name="Оплаченный урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pyments_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "ordering": ["created_at"],
            },
        ),
    ]
