# Generated by Django 5.1 on 2024-11-11 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название курса", max_length=255, verbose_name="Название курса"
                    ),
                ),
                ("description", models.TextField(help_text="Укажите описание курса", verbose_name="Описание курса")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью курса",
                        null=True,
                        upload_to="materials/previews/",
                        verbose_name="Превью курса",
                    ),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
                "db_table": "courses",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название урока", max_length=255, verbose_name="Название урока"
                    ),
                ),
                ("description", models.TextField(help_text="Укажите описание урока", verbose_name="Описание урока")),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите превью урока",
                        null=True,
                        upload_to="materials/previews/",
                        verbose_name="Превью урока",
                    ),
                ),
                (
                    "video_link",
                    models.URLField(
                        help_text="Укажите ссылку на видео", max_length=500, verbose_name="Ссылка на видео"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите курс",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
                "db_table": "lessons",
                "ordering": ["name"],
            },
        ),
    ]
